apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-management
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/saikumar-tec/Hospital-management.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: hospital

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true